baseURL: https://alecmarshall.info/
title: alec-marshall
paginate: 5
theme: charlolamode

menu:
    main:
        - name: Portfolio
          url: /portfolio/
          weight: 10
        - name: Articles
          url: /articles/
          weight: 15
        - name: Amateur Radio
          url: /radio/
          weight: 30

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Alec Marshall
    hideFooter: false
    
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Alec Marshall
        description: |

          Hi, I'm Alec. 
          I build modern geospatial solutions.
        

          Here you will find my portfolio, blog, and some ramblings on Amateur Radio.
        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/JayMarshall"
        - name: linkedin
          url: "https://www.linkedin.com/in/alec-marshall/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true